# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install mdx_truly_sane_lists
- script: pip install https://github.com/mkdocs/mkdocs/archive/9ae04213b9e2ed6625217ca0d6db2bf69a0c1205.tar.gz
- script: pip install --ignore-installed https://github.com/squidfunk/mkdocs-material/archive/f9f48c09c1e33c64cab27250f597e84906c300d5.tar.gz
- script: python --version
- script: mkdocs --version
- script: pip show mkdocs-material | grep -E ^Version
- script: ls -l
- script: mkdocs gh-deploy --verbose --clean --strict
