site_name: Simple public demo for mkdocs
nav:
- home: index.md
theme: 
  name: material
  palette:
    primary: 'white'
    accent: 'blue'
  feature:
    tabs: true
repo_url: https://github.com/sbonds/mkdocs-simple-demo
repo_name: 'GitHub'
edit_uri: tree/master/docs/
extra:
  contact:
    name: 'Steve Bonds'
    email: 'sbonds@gmail.com'
markdown_extensions:
- mdx_truly_sane_lists
