name: build-gh-pages
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build-html:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nested bullet GitHub-style formatting
        run: pip install mdx_truly_sane_lists
      - name: Install mkdocs latest
        run: pip install mkdocs
      - name: Install mkdocs-material latest
        run: pip install mkdocs-material

      # Collect some useful version info
      - name: Get actual installed versions of certain components
        run: |
            python --version
            mkdocs --version
            pip show mkdocs-material | grep -E ^Version
            ls
            
      - name: Build HTML content from Markdown
        run: mkdocs build --verbose --clean --strict

      - name: Show post-build contents of working directory
        run: ls

      - name: Create build artifact of HTML pages
        id: html-content
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  # Based on example at https://github.com/actions/upload-pages-artifact
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-html
    steps:
      - name: Deploy to GitHub Pages
        id: html-content
        uses: actions/deploy-pages@v4
